In [7]:
# Addition of two metrix
import numpy as np

def metrix_addtion(metrix1, metrix2, row, col):
    """this function return sum metrix of two metrix of same diamention"""
    sum_metrix_list = []
    for i in range(len(metrix1)):
        sum_metrix_list.append(metrix1[i]+metrix2[i])
    
    sum_metrix = np.array(sum_metrix_list).reshape(row,col)
    return sum_metrix


count = 2
while count > 0:
    try:
        if count == 2:
            row1 = int(input(f"Enter Mtrix2  Row No."))
            column1 = int(input(f"Enter Mtrix2  column No."))
            element_list1 = []

            for i in range(1,row1+1):
                for j in range(1,column1+1):
                    val = int(input(f"a{i}{j} : "))
                    element_list1.append(val)
        else:
            row2 = int(input(f"Enter Mtrix1  Row No."))
            column2 = int(input(f"Enter Mtrix1  column No."))
            element_list2 = []

            for i in range(1,row2+1):
                for j in range(1,column2+1):
                    val = int(input(f"a{i}{j} : "))
                    element_list2.append(val)

        count = count-1
    except Exception as e:
        print(e)

if row1 == row2 and column1 == column2:
    metrix1 = np.array(element_list1).reshape(row1,column1)
    metrix2 = np.array(element_list2).reshape(row2,column2)
else:
    print(f"please enter same diamention of metrix, metrix1 diamention = [{row1}, {column1}] and metrix2 diamention = [{row2}, {column2}]")
# print(f"{metrix1} + {metrix2} = ")
print(metrix_addtion(element_list1, element_list2, row1, column1))

Enter Mtrix2  Row No.3
Enter Mtrix2  column No.3
a11 : 1
a12 : 2
a13 : 3
a21 : 4
a22 : 5
a23 : 6
a31 : 7
a32 : 8
a33 : 9
Enter Mtrix1  Row No.3
Enter Mtrix1  column No.3
a11 : 1
a12 : 2
a13 : 3
a21 : 4
a22 : 5
a23 : 6
a31 : 7
a32 : 8
a33 : 9
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [32]:
# multiply of two metrix
import numpy as np

def metrix_multiplication(metrix1, metrix2, total_element):
    """this function return multiplication metrix of two metrix"""
#     if row1*column1 = row2*column2:
#         total_element = row1*column1
#     else:
#         a = row1*column1
#         b = row2*column2
#         if a > b:
#             total_element = a
#         else:
#             total_element = b
            
    
    result = np.zeros([column,row],dtype = int)
    
    for i in range(len(metrix1)):
       for j in range(len(metrix2[0])):
           for k in range(len(metrix2)):
               result[i][j] = result[i][j] + (metrix1[i][k] * metrix2[k][j])
        
    print(result)
    
count = 2
while count > 0:
    try:
        if count == 2:
            row1 = int(input(f"Enter Mtrix2  Row No."))
            column1 = int(input(f"Enter Mtrix2  column No."))
            element_list1 = []

            for i in range(1,row1+1):
                for j in range(1,column1+1):
                    val = int(input(f"a{i}{j} : "))
                    element_list1.append(val)
        else:
            row2 = int(input(f"Enter Mtrix1  Row No."))
            column2 = int(input(f"Enter Mtrix1  column No."))
            element_list2 = []

            for i in range(1,row2+1):
                for j in range(1,column2+1):
                    val = int(input(f"a{i}{j} : "))
                    element_list2.append(val)

        count = count-1
    except Exception as e:
        print(e)
        
if row1*column1 > row2*column2:
    total_element = row1*column1
else:
    total_element = row2*column2

metrix1 = np.array(element_list1).reshape(row1, column1)
metrix2 = np.array(element_list2).reshape(row2, column2)

print(f"{metrix1}")
print(f"{metrix2}")

print(metrix_multiplication(metrix1, metrix2, total_element))

Enter Mtrix2  Row No.2
Enter Mtrix2  column No.2
a11 : 1
a12 : 2
a21 : 3
a22 : 4
Enter Mtrix1  Row No.2
Enter Mtrix1  column No.2
a11 : 1
a12 : 2
a21 : 3
a22 : 4
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


IndexError: index 1 is out of bounds for axis 0 with size 1

In [11]:
# Transpose of metrix
import numpy as np

def metrix_transpose(metrix, column, row):
    """this function return Transpose of metrix"""
    result = np.zeros([column,row],dtype = int)
    for i in range(row):
        for j in range(column):
            result[j][i] = metrix[i][j]
    
    return result
    
try:

    row = int(input(f"Enter Mtrix  Row No."))
    column = int(input(f"Enter Mtrix  column No."))
    element_list1 = []

    for i in range(1,row+1):
        for j in range(1,column+1):
            val = int(input(f"a{i}{j} : "))
            element_list1.append(val)
    
    metrix = np.array(element_list1).reshape(row,column)
    print(f"{metrix}")
    print(metrix_transpose(metrix, column, row))
except Exception as e:
    print(e)


Enter Mtrix  Row No.1
Enter Mtrix  column No.6
a11 : 1
a12 : 2
a13 : 3
a14 : 4
a15 : 5
a16 : 6
[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [29]:
def sort_word_alphabetic_order(input_string):
    """this function sort word in alphabetic order"""
    word_sorted_list = []
    words = input_string.lower().split(" ")
    words.sort()  
    # display the sorted words  
    for word in words: 
        word_sorted_list.append(word)
        print(word)  
    return word_sorted_list
string = input("Enter Line : ")
sort_word_alphabetic_order(string)


Enter Line : i am ved prakash sharma and i am learning data Science From ineuron
am
am
and
data
from
i
i
ineuron
learning
prakash
science
sharma
ved


['am',
 'am',
 'and',
 'data',
 'from',
 'i',
 'i',
 'ineuron',
 'learning',
 'prakash',
 'science',
 'sharma',
 'ved']

In [30]:
punc = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

def remove_punctuation(string):
    """this function remove punctuation and return a string"""
    for ele in string:
        if ele in punc:
            string = string.replace(ele, "")
    
    return string

string = input("Enter String : ")
print(remove_punctuation(string))

Enter String : hbjdksb[;/.d'fs;m834uuiuy34hyhucdnjn23e;'!jhb5444655
hbjdksbdfsm834uuiuy34hyhucdnjn23ejhb5444655
